import { Decimal } from '@/lib/decimal';
export type ClosedTrade={status:string;pnl_usd:string|null;r_multiple:string|null;trade_date?:string};
const d=(v:string|null|undefined)=>new Decimal(v??0);
export function computeTradingMetrics(trades:ClosedTrade[]){
 const closed=trades.filter(t=>['WON','LOST','BREAK_EVEN'].includes(t.status));const wins=closed.filter(t=>t.status==='WON');const losses=closed.filter(t=>t.status==='LOST');const grossProfit=wins.reduce((a,t)=>a.add(d(t.pnl_usd)),new Decimal(0));const grossLoss=losses.reduce((a,t)=>a.add(d(t.pnl_usd).abs()),new Decimal(0));const net=closed.reduce((a,t)=>a.add(d(t.pnl_usd)),new Decimal(0));const pf=grossLoss.eq(0)?null:grossProfit.div(grossLoss);const avgWin=wins.length?grossProfit.div(wins.length):new Decimal(0);const avgLoss=losses.length?grossLoss.div(losses.length):new Decimal(0);const winRate=closed.length?new Decimal(wins.length).div(closed.length).mul(100):new Decimal(0);const lossRate=closed.length?new Decimal(losses.length).div(closed.length).mul(100):new Decimal(0);const expectancy=closed.length?net.div(closed.length):new Decimal(0);const rs=closed.filter(t=>t.r_multiple!=null);const avgR=rs.length?rs.reduce((a,t)=>a.add(d(t.r_multiple)),new Decimal(0)).div(rs.length):new Decimal(0);
 let equity=new Decimal(0),peak=new Decimal(0),maxDd=new Decimal(0),winStreak=0,lossStreak=0,maxWin=0,maxLoss=0;for(const t of [...closed].reverse()){equity=equity.add(d(t.pnl_usd));peak=Decimal.max(peak,equity);maxDd=Decimal.max(maxDd,peak.sub(equity));if(t.status==='WON'){winStreak++;lossStreak=0;maxWin=Math.max(maxWin,winStreak)}else if(t.status==='LOST'){lossStreak++;winStreak=0;maxLoss=Math.max(maxLoss,lossStreak)}else{winStreak=lossStreak=0}}
 return{total:closed.length,wins:wins.length,losses:losses.length,breakEven:closed.filter(t=>t.status==='BREAK_EVEN').length,net,winRate,lossRate,profitFactor:pf,averageWin:avgWin,averageLoss:avgLoss,expectancy,averageR:avgR,maxDrawdown:maxDd,maxWinStreak:maxWin,maxLossStreak:maxLoss};
}
export function monthlyGrowth(start:string,current:string){const s=d(start),c=d(current);return s.eq(0)?new Decimal(0):c.sub(s).div(s).mul(100)}
